### ISSUE TITLE
token function to receive currentPos instead of nextPos

### ISSUE THREAD

**Issue by chamini2** [mrkkrp/megaparsec#70]
I know the `token` function receives a function with signature `Int -> SourcePos -> t -> SourcePos` to calculate the position of the next token, however, in my particular case, I can't give such a function, since I don't know how many spaces there may be between tokens.

Is there any chance to get a `token` that instead receives a function that gives the `SourcePos` of the **current** token?

I suppose that you ask for `nextPos` for design purposes, and it may be a hard change, or even impossible with the current state of the library, but I wanted to know if it's possible.

**Comment by mrkkrp** [comment]
Please give realistic example when this would be useful. If it's a god idea, we could add one more version of `token` function.

**Comment by chamini2** [comment]
Well, I have a parser on a `data` that's been already parsed using `alex` and `happy`, this tokens store the location span information (i.e. where in the file it starts and where it ends), but in the lexer (`alex`), I just ignore whitespace, so an expression with the form

    x=2

parses the same as

    x       =        
                 2

Both of this give me the same information to be parsed, the only different information is source location, working with tokens like this, there's no way to infer the next token's position, as it could be at the end of this token (like in the first example), or on the next line (like in the second example).

For clarification, my current `token` function usage looks a bit like this:

    class Span a where
            getSpan :: a -> SrcSpan

    satisfy' :: Span x => (x -> Either [Message] x) -> Parsec [x] x
    satisfy' guard = token nextPos guard
        where
            nextPos :: Int -> SourcePos -> x -> SourcePos
            nextPos _ _ x = spanToPos (getSpan x)

`spanToPos` gets the ending position of the `SourceSpan`.

So I'm just ignoring the last `SourcePos`, since there's no information it can provide.

This means that all my error messages are positioned a few spaces before than it should.

**Comment by mrkkrp** [comment]
I've not used `alex`, so let's clarify your situation a bit. You run `alex` on your input and it produces collection of tokens, every token has associated position (where it starts in input file and where it ends) and its somewhat normalized form where `x = 2` is the same as `x=2` (I mean you still have it as textual fragment, right?). Now you want to parse this fragment using Megaparsec.

Please correct me if I'm wrong.

**Comment by mrkkrp** [comment]
I understand what you mean, there will be new version of `token` in Megaparsec 4.3.0 tailored exactly for this approach to parsing. Thanks for the report.

**Comment by mrkkrp** [comment]
@chamini2, There is something for this on master now. Can you try it and give some feedback?

**Comment by chamini2** [comment]
@mrkkrp, I think the original post in this issue wasn't clear, I'm sorry for that, I meant that the `token'` function received a function `t -> SorucePos`

    token' :: (t -> SourcePos) -> (t -> Either [Message] a) -> m a

And a `pToken'` function

        pToken' :: Stream s t
               => (t -> SourcePos)
               -> (t -> Either [Message] a)
               -> ParsecT s m a
        pToken' currpos test = ParsecT $ \(State input pos w) cok _ _ eerr ->
          case uncons input of
            Nothing     -> eerr (unexpectedErr eoi pos)
            Just (c,cs) -> let newpos = currpos c in
              case test c of
                Left ms -> eerr (newErrorMessages ms newpos)
                Right x -> let newstate = State cs newpos w
                           in newstate `seq` cok x newstate mempty

But when testing it, it seems the error position is reverted to the last correct token found, so in the error messages, it still is one token behind.

**Comment by mrkkrp** [comment]
@chamini2, Sorry, that initial version is indeed hard to use (wrote it a bit automatically) :-) I've pushed updated version which takes `(t -> SoucePos)`, that should be better.

**Comment by chamini2** [comment]
I've cloned the repo to test this, and it is still not working, so I added to `Prim.hs` an import of `Debug.Trace`, and added a trace to a line, to test something:

    import Debug.Trace

    pToken' :: Stream s t
           => (t -> SourcePos)
           -> (t -> Either [Message] a)
           -> ParsecT s m a
    pToken' getpos test = ParsecT $ \(State input pos w) cok _ _ eerr ->
      case uncons input of
        Nothing     -> eerr (tt pos (show eoi) $ unexpectedErr eoi pos)
        Just (c,cs) ->
          let !nextpos = getpos c
          in case test c of
            Left ms -> eerr (tt nextpos (show ms) $ newErrorMessages ms nextpos)      -- here is the change
            Right x -> let newstate = State cs nextpos w
                       in newstate `seq` cok x newstate mempty
        where
                tt ps str = trace ("---- " ++ show ps ++ ": " ++ str)

The output of the test I did was:

    ---- test/mixfix/fail.ang:15:7: [Unexpected "==",Expected "identifier"]
    test/mixfix/fail.ang:15:5:
        ERROR: in mixfix parser,
            unexpected ==
            expected end of input or identifier

So, somewhere after the error messages are set, the position is set to the last valid token.

**Comment by chamini2** [comment]
I've found a solution, I don't know if you'll consider it viable, but it works. I also use an `eof` parser, and that was updating the position of the error message, so I added an `eof'` parser, which takes a function just like `token'`:

      eof' :: (t -> SourcePos) -> m ()

And the `pEof'` function

    pEof' :: Stream s t => (t -> SourcePos) -> ParsecT s m ()
    pEof' getpos = label eoi $ ParsecT $ \s@(State input pos _) _ _ eok eerr ->
      case uncons input of
        Nothing    -> eok () s mempty
        Just (x,_) -> eerr (unexpectedErr (showToken x) (getpos x))
    {-# INLINE pEof' #-}

**Comment by mrkkrp** [comment]
This is getting very ad hoc and it's not acceptable, there is no way we can get along with `eof'`. Normal `eof` should work here as well. `token'` should be the signle function where we can tune things up for this approach.

Now I see why this happens. `eof` uses last known position in input stream when it fails, as currently written `token'` sets position to beginning of last processed element, thus we have this difference. Also this will show up when you try to parse token that isn't there, `Nothing` alternative in `token'` uses last known position as well (that's all it's got after all).

The only way to solve this issue properly is to get position where current element ends as well. I don't know if your `SrcSpan` provides it, but you could calculate it as sum of beginning position and length of actual element (this is a bit naive approach but it should work in most cases). If we have this position as well, we just set it on success when we call `cok` and then when next thing fails we get right position. Note that in order to work properly, spans should be placed like this:

```
x         =         2
^ 1 token ^ 2 token ^ ...

```

…i.e. we should consider trailing whitespace as part of token, at least when we calculate its end position. So, this is how this can be done in acceptable manner.

----

Combination of external tokenizers and Parsec emerged probably because of awkward (so to say) support for tokenizing in Parsec itself. Why don't you just try `Text.Megaparsec.Lexer` to write your tokenizer as well? This shouldn't be too difficult, and you'll have entire parser thing working quite smoothly. What exactly makes you use external tokenizers with Megaparsec? If you can give your reasons, perhaps we could proceed in that direction instead to eliminate this need.

**Comment by chamini2** [comment]
I completely understand that it is an ad hoc solution, although those two functions and maybe `tokens` are the ones to add the `getpos` version, since those are the functions with an `uncons` call.

I use `alex` and `happy`, and in `alex` (the tokenizer) I ignore whitespace completely, so I **do** have the end position of the token, but not including the whitespace.

*****

> The only way to solve this issue properly is to get position where current element ends as well. I don't know if your SrcSpan provides it, but you could calculate it as sum of beginning position and length of actual element (this is a bit naive approach but it should work in most cases). If we have this position as well, we just set it on success when we call cok and then when next thing fails we get right position. 

This approach is intended for `token`, right? because that's what I did before you agreed to include `token'`, and it works in most cases, but when the token is on the next line, it indicates the line above the real parser error.

**Comment by mrkkrp** [comment]
> I use alex and happy, and in alex (the tokenizer) I ignore whitespace completely, so I do have the end position of the token, but not including the whitespace.

By ignoring whitespace (and not including into into length of token) you're removing information that's necessary for correct reporting of error messages in some cases. This is not going to work.

I probably should revert last changes and close this as “wontfix”. You can do intermediate processing of token stream to create gap-less stream like this:

```
first_token                     second_token
^          ^→ shift it to this →^
```

So end of one token is the beginning of the other. You'll have a bit special case with the last token though. Sorry that's all I can propose here. Best solution is probably build entire thing with Megaparsec without other libraries.

**Comment by chamini2** [comment]
Well, I understand, I'd like it if you leave the `token' :: (t -> (SourcePos, SorucePos)) -> (t -> Either [Message] a) -> m a` version in, but it's OK if you feel it's not appropriate.

**Comment by mrkkrp** [comment]
For now, let's suspend this thing. This solution with `token' :: (t -> (SourcePos, SoucePos)) -> …` doesn't feel solid enough for me, but I may be mistaken and I'm not the only consumer of this library, so I understand that my own experiences and use-cases don't cover everything people might want to do with Megaparsec.

One thing I don't like is that `token'` is not a drop-in replacement for `token` to facilitate work with tools like Alex. The new “primitive” requires thorough description why you might want to use it and how to prepare the rest of your program in order to get good results with it.

If more people express need for this or opinions about it, I'll return to this. I'll keep this issue open and I'll make it with “discussion” tag.

**Comment by mrkkrp** [comment]
@chamini2, Please see propositions in #83. In Megaparsec 5.0.0 there will be breaking changes, one of them is that position-advancing functions will likely be in `Stream` type-class, not in arguments of `token` function. Now, when we get to this, I'm open to add alternative functions to that type class, that could read position information directly from token. We will need to think about it, so all use-cases are covered. I will ping you when it's time and you will be able to propose any breakning changes into entire mechanism of position changing that work for you to be incorporated in that release of Megaparsec. What do you think?

**Comment by chamini2** [comment]
Awesome, let me know to brainstorm if needed!

**Comment by mrkkrp** [comment]
I'm closing this, should be fixed by #94. I would be great if you find a change to try the new feature before Megaparsec 5.0.0 is released.

**Comment by chamini2** [comment]
Hey, I'll definitely check it out. I have the next couple of weeks very busy, but as soon as I get a chance I'll update you about the results. 

Although I did see some of the changes in #94 and it looks really promising!

Thank you for taking the time to develop this.

**Comment by mrkkrp** [comment]
There is no hurry, I think we have a couple of months for sure :-)
